title: Multisite Index
description: Multisite Index für Multisite ermöglicht netzwerkweites Suchen und Teilen. Erschließe neue Möglichkeiten zum Suchen und Anzeigen von Inhalten, indem Du Beiträge von beliebigen Webseiten in Deinem Netzwerk in einem Index zusammenfasst
