title: Multisite Beitragsindex
description: Multisite Beitragsindex für Multisite ermöglicht netzwerkweites Suchen und Teilen. Erschließe neue Möglichkeiten zum Suchen und Anzeigen von Inhalten, indem Du Beiträge von beliebigen Webseiten in Deinem Netzwerk in einem Index zusammenfasst
